version: '3'
services:
  web:
    image: nginx:latest
    container_name: phpdevenv-nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/app
      - ../config/default.conf:/etc/nginx/conf.d/default.conf
      - ../logs:/var/log/nginx
    depends_on:
      - php
  php:
    image: php:7-fpm
    container_name: phpdevenv-php7
    volumes: 
      - ../src:/app
      - ../config/php-logs.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  composer:
    image: composer:latest
    container_name: phpdevenv-composer
    volumes:
      - ../src:/app
